server:
  port: 8081
  servlet:
    context-path: /api

logging:
  level:
    root: warn
    ziv.pra.relean: debug
  file:
    path: logs/dev.log
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/books?useUnicode=true&characterEncoding=utf-8
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true